import {
  addApolloStateAndReturnPageProps,
  initializeApollo,
} from "@/config/gqlClient";
import { GET_PHOTOS } from "@/gql/query";
import { PhotoCard } from "@/ui/Photos/Card";
import Sidebar from "@/ui/Sidebar";
import { useLazyQuery } from "@apollo/client";
import { PhotoData } from "@type-photos";
import { Masonry, useInfiniteLoader } from "masonic";
import { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";

let page = 0;

export default function Page({ data }: { data: PhotoData[] }) {
  const [items, setItems] = useState<PhotoData[]>(data);

  const [fetchData, { loading, error }] = useLazyQuery<{
    photos: PhotoData[];
  }>(GET_PHOTOS, {
    variables: {
      page,
    },
    onCompleted(data) {
      setItems((prev) => [...prev, ...data.photos]);
    },
  });

  // 무한 스크롤
  const maybeLoadMore = useInfiniteLoader(
    async (start, end, currentItems) => {
      if (!loading) {
        fetchData();
        page += 1;
      }
    },
    {
      isItemLoaded: (index, items) => !!items[index],
      minimumBatchSize: 30, // 한 번에 로드할 항목의 최소 개수
      threshold: 3, // 데이터를 미리 가져올 임계점
      // number: number // 최종 로드해야할 총 항목의 수 (알고 있는 경우에 입력)
    }
  );

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  return (
    <Masonry
      onRender={maybeLoadMore}
      items={items}
      columnGutter={30}
      columnWidth={347}
      overscanBy={1.25}
      render={PhotoCard}
    />
  );
}

Page.getLayout = function getLayout(page: NextPage) {
  return (
    <>
      <Head>
        <title>Photos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex w-full">
        <Sidebar />
        <section className="flex flex-col box-border rounded-xl w-full mt-[101px] mx-5 ">
          <header className="z-1 fixed top-0 flex align-center w-full h-[101px] bg-white"></header>
          <>{page}</>
        </section>
      </main>
    </>
  );
};

// 개발 모드에서는 getStaticProps가 대신 각 요청에서 실행됩니다.
export async function getServerSideProps() {
  const apolloClient = initializeApollo();

  const { data } = await apolloClient.query<{ photos: PhotoData[] }>({
    query: GET_PHOTOS,
    variables: {
      page,
    },
  });

  return addApolloStateAndReturnPageProps(apolloClient, {
    props: {
      data: data.photos,
    },
  });
}
